#!/usr/bin/env python

import datetime
import pytz

timezones = (
    'Asia/Taipei',
    'America/New_York',
    'Pacific/Honolulu',
)

if __name__ == '__main__':
    #fmt = '%A %Y-%m-%d %H:%M:%S %Z%z'
    fmt = '%A %Y-%m-%d %H:%M'

    utc = pytz.utc
    utc_now = utc.localize(datetime.datetime.utcnow())

    for tz_name in timezones:
        tz = pytz.timezone(tz_name)
        tz_now = utc_now.astimezone(tz)
        print('{tz_name}: {local_datetime}'.format(
            tz_name = tz_name,
            local_datetime = tz_now.strftime(fmt)
        ))
        #Importing all the necessary libraries to form the alarm clock:
from tkinter import *
import datetime
import time
import winsound
def alarm(set_alarm_timer):
    while True:
        time.sleep(1)
        current_time = datetime.datetime.now()
        now = current_time.strftime("%H:%M:%S")
        date = current_time.strftime("%d/%m/%Y")
        print("The Set Date is:",date)
        print(now)
        if now == set_alarm_timer:
            print("Time to Wake up")
        winsound.PlaySound("sound.wav",winsound.SND_ASYNC)
        break
def actual_time():
    set_alarm_timer = f"{hour.get()}:{min.get()}:{sec.get()}"
    alarm(set_alarm_timer)
